### ISSUE TITLE
docs: Update README.md

### ISSUE THREAD

**Issue by alvinphilips** [polarvoid/moon-engine#10]
Currently, the README file, particularly the section on how to interact with the Demo is outdated.

The instructions and controls are for a previous demo that was a 3D camera you could fly around with.

The new demo showcases the Particle System and the Renderer.

Try to update the README with the correct information.

The new controls are as follows:
- Keys `1`, `2` and `3` for pausing and resuming each particle effect respectively.
- `R` to restart all the Particle Effects.
- `WASD` keys to move the `Smoke` particle system.
- `Mouse Pointer` to move the blueish default particle system.

Checklist of things to be done:
- [ ] Add information about the Particle System Demo.
- [ ] Modify the controls table to show the controls of the new Demo.
- [ ] (Optionally) Add a PNG/GIF of the demo to the README.

**Comment by JoeKiesche** [comment]
I can work on this!

**Comment by elishaestibeiro** [comment]
Hey Alvin, can I give this a try?

**Comment by alvinphilips** [comment]
Hey @Joek3133 , thank you for your interest, however this issue was assigned on a first come basis. I'll be opening up more issues soon, perhaps you can take a look at them? :)

**Comment by alvinphilips** [comment]
Hey @elishaestibeiro , you can start working on this. Feel free to contact me by either commenting here, or opening up a Pull Request. Thank you :)
