### ISSUE TITLE
Clarify wasm-pack usage

### ISSUE THREAD

**Issue by elishaestibeiro** [polarvoid/moon-engine#12]
Hey! While I was going through the instructions to install Moon Engine, I was a bit confused about a certain thing. 

In the beginning, you've mentioned about installing `wasm-pack` and then after a couple of lines, said to build `wasm-pack` by using the link you mentioned. It was a bit confusing to understand and a few changes could be made for a easier walkthrough. 

I would like to work on this, if you'd be okay with it. :)

**Comment by alvinphilips** [comment]
Sure, that sounds great @elishaestibeiro. Open up a PR and I'd love to update it to be more helpful :) Thanks for reaching out about this.
